export const trafficKeywords = [
    { id: 10, keywordEnum: 'VEHICLE', keywordName: '버스', vehicleType: 'BUS' },
    { id: 11, keywordEnum: 'VEHICLE', keywordName: '자가용', vehicleType: 'CAR' },
    { id: 9999, keywordEnum: '', keywordName: '지하철', vehicleType: '' },
];
export const issueKeywords = [
    { id: 1, keywordEnum: 'ISSUE', keywordName: '시위', vehicleType: null },
    { id: 2, keywordEnum: 'ISSUE', keywordName: '연착', vehicleType: null },
    { id: 3, keywordEnum: 'ISSUE', keywordName: '자연재해', vehicleType: null },
    { id: 4, keywordEnum: 'ISSUE', keywordName: '공사', vehicleType: null },
    { id: 5, keywordEnum: 'ISSUE', keywordName: '혼잡', vehicleType: null },
    { id: 6, keywordEnum: 'ISSUE', keywordName: '사고', vehicleType: null },
    { id: 7, keywordEnum: 'ISSUE', keywordName: '도로정체', vehicleType: null },
    { id: 8, keywordEnum: 'ISSUE', keywordName: '행사', vehicleType: null },
    { id: 9, keywordEnum: 'ISSUE', keywordName: '기타', vehicleType: null },
];
export const issueKeywordsNotEtc = [
    { id: 1, keywordEnum: 'ISSUE', keywordName: '시위', vehicleType: null },
    { id: 2, keywordEnum: 'ISSUE', keywordName: '연착', vehicleType: null },
    { id: 3, keywordEnum: 'ISSUE', keywordName: '자연재해', vehicleType: null },
    { id: 4, keywordEnum: 'ISSUE', keywordName: '공사', vehicleType: null },
    { id: 5, keywordEnum: 'ISSUE', keywordName: '혼잡', vehicleType: null },
    { id: 6, keywordEnum: 'ISSUE', keywordName: '사고', vehicleType: null },
    { id: 7, keywordEnum: 'ISSUE', keywordName: '도로정체', vehicleType: null },
    { id: 8, keywordEnum: 'ISSUE', keywordName: '행사', vehicleType: null },
];
export const subwayKeywords = [
    { id: 9998, keywordEnum: 'VEHICLE', keywordName: '전체', vehicleType: 'SUBWAY' },
    { id: 13, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '1호선' },
    { id: 14, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '2호선' },
    { id: 15, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '3호선' },
    { id: 16, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '4호선' },
    { id: 17, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '5호선' },
    { id: 18, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '6호선' },
    { id: 19, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '7호선' },
    { id: 20, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '8호선' },
    { id: 21, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '9호선' },
    { id: 26, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '신분당선' },
    { id: 25, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '공항철도' },
    { id: 24, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '수인분당선' },
    { id: 27, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '경의중앙선' },
    { id: 34, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '김포도시철도' },
    { id: 22, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '인천1호선' },
    { id: 23, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '인천2호선' },
    { id: 29, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '에버라인' },
    { id: 30, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '의정부경전철' },
    { id: 33, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '우이신형경전철' },
    { id: 32, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '경강선' },
    { id: 31, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '서해선' },
    { id: 28, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '경춘선' },
    { id: 35, keywordEnum: 'VEHICLE', vehicleType: 'SUBWAY', keywordName: '인천공항자기부상철도' },
];
