export const trafficKeywords = [
    { id: 9, keywordEnum: 'VEHICLE', keywordName: '버스', vehicleType: 'BUS' },
    { id: 10, keywordEnum: 'VEHICLE', keywordName: '자가용', vehicleType: 'CAR' },
    { id: 9999, keywordEnum: '', keywordName: '지하철', vehicleType: '' },
];
export const issueKeywords = [
    { id: 1, keywordEnum: 'ISSUE', keywordName: '시위', vehicleType: null },
    { id: 2, keywordEnum: 'ISSUE', keywordName: '연착', vehicleType: null },
    { id: 3, keywordEnum: 'ISSUE', keywordName: '자연재해', vehicleType: null },
    { id: 4, keywordEnum: 'ISSUE', keywordName: '공사', vehicleType: null },
    { id: 5, keywordEnum: 'ISSUE', keywordName: '혼잡', vehicleType: null },
    { id: 6, keywordEnum: 'ISSUE', keywordName: '도로정체', vehicleType: null },
    { id: 7, keywordEnum: 'ISSUE', keywordName: '행사', vehicleType: null },
    { id: 8, keywordEnum: 'ISSUE', keywordName: '기타', vehicleType: null },
];
export const subwayKeywords = [
    { id: 11, keywordEnum: 'VEHICLE', keywordName: '1호선', vehicleType: 'SUBWAY' },
    { id: 12, keywordEnum: 'VEHICLE', keywordName: '2호선', vehicleType: 'SUBWAY' },
    { id: 13, keywordEnum: 'VEHICLE', keywordName: '3호선', vehicleType: 'SUBWAY' },
    { id: 14, keywordEnum: 'VEHICLE', keywordName: '4호선', vehicleType: 'SUBWAY' },
    { id: 15, keywordEnum: 'VEHICLE', keywordName: '5호선', vehicleType: 'SUBWAY' },
    { id: 16, keywordEnum: 'VEHICLE', keywordName: '6호선', vehicleType: 'SUBWAY' },
    { id: 17, keywordEnum: 'VEHICLE', keywordName: '7호선', vehicleType: 'SUBWAY' },
    { id: 18, keywordEnum: 'VEHICLE', keywordName: '8호선', vehicleType: 'SUBWAY' },
    { id: 19, keywordEnum: 'VEHICLE', keywordName: '9호선', vehicleType: 'SUBWAY' },
    { id: 20, keywordEnum: 'VEHICLE', keywordName: '인천1호선', vehicleType: 'SUBWAY' },
    { id: 21, keywordEnum: 'VEHICLE', keywordName: '인천2호선', vehicleType: 'SUBWAY' },
    { id: 22, keywordEnum: 'VEHICLE', keywordName: '수인분당선', vehicleType: 'SUBWAY' },
    { id: 23, keywordEnum: 'VEHICLE', keywordName: '공항철도', vehicleType: 'SUBWAY' },
    { id: 24, keywordEnum: 'VEHICLE', keywordName: '신분당선', vehicleType: 'SUBWAY' },
    { id: 25, keywordEnum: 'VEHICLE', keywordName: '경의중앙선', vehicleType: 'SUBWAY' },
    { id: 26, keywordEnum: 'VEHICLE', keywordName: '경춘선', vehicleType: 'SUBWAY' },
    { id: 27, keywordEnum: 'VEHICLE', keywordName: '에버라인', vehicleType: 'SUBWAY' },
    { id: 28, keywordEnum: 'VEHICLE', keywordName: '의정부경전철', vehicleType: 'SUBWAY' },
    { id: 29, keywordEnum: 'VEHICLE', keywordName: '서해선', vehicleType: 'SUBWAY' },
    { id: 30, keywordEnum: 'VEHICLE', keywordName: '경강선', vehicleType: 'SUBWAY' },
    { id: 31, keywordEnum: 'VEHICLE', keywordName: '우이신형경전철', vehicleType: 'SUBWAY' },
    { id: 32, keywordEnum: 'VEHICLE', keywordName: '김포도시철도', vehicleType: 'SUBWAY' },
    { id: 33, keywordEnum: 'VEHICLE', keywordName: '인천공항자기부상철도', vehicleType: 'SUBWAY' },
];
